export {default as Home} from './home/home'
export {default as Admin} from './admin/admin'
export {default as Contact} from './contact/contact'
export {default as OrderHistory} from './orderHistory/orderHistory'
export {default as Login} from './auth/login'
export {default as Register} from './auth/register'
export {default as Reset} from './auth/reset'